# PVP регулируется правом `simplepvp.gamemode.<gamemode>`
# Например игроки, у которых есть право `simplepvp.gamemode.creative` могут бить игроков в режиме креатива

# Запускать тайпер ПВП режима при атаке другого игрока (не включается для игроков с правом `simplepvp.timer.bypass`)
pvp-timer: true

# Длительность ПВП режима
pvp-time: 10

# Убивать игрока при выходе из игры во время ПВП режима
exit-pvp-kill: true

# Эти команды нельзя использовать во время ПВП режима
blocked-cmds:
  - '/spawn'
  - '/tp'
  - '/tpo'

# Эти предметы нельзя использовать во время ПВП режима
blocked-items:
  - 'firework_rockets'

# -=-=-=-=-=- СООБЩЕНИЯ -=-=-=-=-=-
# Для цвета используйте символ '§'
# Если хотите отключить любое сообщение, то сделайте его пустым

# ActionBar во время ПВП режима
on-pvp-msg: '§cДо выхода из §lPVP§c осталось §e{time}§c секунд'

# Показывается при вводе запрещенной команды во время ПВП режима
command-on-pvp-msg: '§f[§4§lPVP§r§f] §cВы не можете выполнять данную команду во время PVP'

# Показывается при использование запрещённого предмета во время ПВП режима
item-on-pvp-msg: '§f[§4§lPVP§r§f] §cВы не можете использовать данный предмет во время PVP'

# Рассылается всем игрокам на сервере, если игрок вышел во время ПВП
exit-on-pvp-msg: '§f[§4§lPVP§r§f] §e{player} вышел во время §cPVP§e и был наказан!'

# ActionBar когда ПВП режим заканчивается
end-pvp-msg: '§aВы вышли из §lPVP§r§a режима'

# Показывается, когда игрок не обладает правом для ПВП в его текущем режиме
no-permission-msg: '§cУ вас нет прав для PVP в данном режиме'
